[package]
name = "mh-1"
version = "0.1.0"
authors = ["Will O'Brien <will.obrien@adarga.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gmp-mpfr-sys = "1.3"